apiVersion: v1
kind: Service
metadata:
  name: '{DEPLOYMENT_NAME}'
spec:
  selector:
    app: '{DEPLOYMENT_NAME}'
  ports:
    - protocol: TCP
      port: {EXTERNAL_PORT}
      targetPort: {WRAPPER_PORT}
  type: '{SERVICE_TYPE}'