---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  '{DEPLOYMENT_NAME}'
  labels:
    app: '{LABEL_APP}'
    project: '{LABEL_PROJECT}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {DEPLOYMENT_NAME}
  template:
    metadata:
      labels:
        app: {DEPLOYMENT_NAME}
    spec:
      containers:
      - name: app
        image: {DEPLOYMENT_IMAGE}
        imagePullPolicy: Always
        env: []
        ports:
        - containerPort: {WRAPPER_PORT}
        readinessProbe:
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 20
          httpGet:
            path: "/"
            port: {WRAPPER_PORT}
            scheme: HTTP
        resources:
          limits:
            cpu: {DEPLOYMENT_CPU_LIMIT}
            memory: {DEPLOYMENT_MEMORY_LIMIT}
          requests:
            cpu: {DEPLOYMENT_CPU_REQUEST}
            memory: {DEPLOYMENT_MEMORY_REQUEST}